/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * DX Template API
 * Development documentation
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

export interface AuthUser {
  id: string;
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  emailVerified: boolean;
  image: string | null;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  createdAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  updatedAt: string;
}

export interface Error {
  code: string;
  message: string;
}

export interface ImageUploadUrl {
  uploadUrl: string;
  objectKey: string;
  publicUrl?: string;
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum 0
   */
  expiresIn: number;
}

export type CreateImageUploadUrlInputContentType =
  (typeof CreateImageUploadUrlInputContentType)[keyof typeof CreateImageUploadUrlInputContentType];

export const CreateImageUploadUrlInputContentType = {
  "image/jpeg": "image/jpeg",
  "image/png": "image/png",
  "image/webp": "image/webp",
} as const;

export interface CreateImageUploadUrlInput {
  /**
   * @minLength 1
   * @maxLength 255
   */
  fileName: string;
  contentType: CreateImageUploadUrlInputContentType;
  /**
   * @maximum 20971520
   * @exclusiveMinimum 0
   */
  contentLength: number;
}

export interface User {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  slackUserId: string;
  displayName: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  createdAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  updatedAt: string;
}

export interface CreateUserInput {
  /** @minLength 1 */
  slackUserId: string;
  /** @minLength 1 */
  displayName: string;
}

export type GetApiHealth200 = {
  status: "ok";
};

export type GetApiMe200 = {
  user: AuthUser;
};

export type PostApiUploadsImagesPresign201 = {
  upload: ImageUploadUrl;
};

export type GetApiUsers200 = {
  users: User[];
};

export type PostApiUsers201 = {
  user: User;
};

export type GetApiUsersBySlackUserId200 = {
  user: User;
};

export type getApiHealthResponse200 = {
  data: GetApiHealth200;
  status: 200;
};

export type getApiHealthResponseSuccess = getApiHealthResponse200 & {
  headers: Headers;
};

export type getApiHealthResponse = getApiHealthResponseSuccess;

export const getGetApiHealthUrl = () => {
  return `/api/health`;
};

export const getApiHealth = async (options?: RequestInit): Promise<getApiHealthResponse> => {
  const res = await fetch(getGetApiHealthUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiHealthResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getApiHealthResponse;
};

export const getGetApiHealthQueryKey = () => {
  return [`/api/health`] as const;
};

export const getGetApiHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiHealth>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>>;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiHealthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiHealth>>> = ({ signal }) =>
    getApiHealth({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiHealth>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getApiHealth>>>;
export type GetApiHealthQueryError = unknown;

export function useGetApiHealth<TData = Awaited<ReturnType<typeof getApiHealth>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiHealth>>,
          TError,
          Awaited<ReturnType<typeof getApiHealth>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiHealth<TData = Awaited<ReturnType<typeof getApiHealth>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiHealth>>,
          TError,
          Awaited<ReturnType<typeof getApiHealth>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiHealth<TData = Awaited<ReturnType<typeof getApiHealth>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiHealth<TData = Awaited<ReturnType<typeof getApiHealth>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiHealthQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetApiHealthSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiHealth>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>>;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiHealthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiHealth>>> = ({ signal }) =>
    getApiHealth({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getApiHealth>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiHealthSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiHealth>>>;
export type GetApiHealthSuspenseQueryError = unknown;

export function useGetApiHealthSuspense<
  TData = Awaited<ReturnType<typeof getApiHealth>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiHealthSuspense<
  TData = Awaited<ReturnType<typeof getApiHealth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiHealthSuspense<
  TData = Awaited<ReturnType<typeof getApiHealth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiHealthSuspense<
  TData = Awaited<ReturnType<typeof getApiHealth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiHealthSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type getApiMeResponse200 = {
  data: GetApiMe200;
  status: 200;
};

export type getApiMeResponse401 = {
  data: Error;
  status: 401;
};

export type getApiMeResponseSuccess = getApiMeResponse200 & {
  headers: Headers;
};
export type getApiMeResponseError = getApiMeResponse401 & {
  headers: Headers;
};

export type getApiMeResponse = getApiMeResponseSuccess | getApiMeResponseError;

export const getGetApiMeUrl = () => {
  return `/api/me`;
};

export const getApiMe = async (options?: RequestInit): Promise<getApiMeResponse> => {
  const res = await fetch(getGetApiMeUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiMeResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getApiMeResponse;
};

export const getGetApiMeQueryKey = () => {
  return [`/api/me`] as const;
};

export const getGetApiMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = Error,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>>;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMe>>> = ({ signal }) =>
    getApiMe({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiMeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMe>>>;
export type GetApiMeQueryError = Error;

export function useGetApiMe<TData = Awaited<ReturnType<typeof getApiMe>>, TError = Error>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMe>>,
          TError,
          Awaited<ReturnType<typeof getApiMe>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiMe<TData = Awaited<ReturnType<typeof getApiMe>>, TError = Error>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMe>>,
          TError,
          Awaited<ReturnType<typeof getApiMe>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiMe<TData = Awaited<ReturnType<typeof getApiMe>>, TError = Error>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiMe<TData = Awaited<ReturnType<typeof getApiMe>>, TError = Error>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetApiMeSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = Error,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>>;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMe>>> = ({ signal }) =>
    getApiMe({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getApiMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiMeSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMe>>>;
export type GetApiMeSuspenseQueryError = Error;

export function useGetApiMeSuspense<TData = Awaited<ReturnType<typeof getApiMe>>, TError = Error>(
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiMeSuspense<TData = Awaited<ReturnType<typeof getApiMe>>, TError = Error>(
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiMeSuspense<TData = Awaited<ReturnType<typeof getApiMe>>, TError = Error>(
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiMeSuspense<TData = Awaited<ReturnType<typeof getApiMe>>, TError = Error>(
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiMeSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type postApiUploadsImagesPresignResponse201 = {
  data: PostApiUploadsImagesPresign201;
  status: 201;
};

export type postApiUploadsImagesPresignResponse400 = {
  data: Error;
  status: 400;
};

export type postApiUploadsImagesPresignResponse401 = {
  data: Error;
  status: 401;
};

export type postApiUploadsImagesPresignResponse500 = {
  data: Error;
  status: 500;
};

export type postApiUploadsImagesPresignResponseSuccess = postApiUploadsImagesPresignResponse201 & {
  headers: Headers;
};
export type postApiUploadsImagesPresignResponseError = (
  | postApiUploadsImagesPresignResponse400
  | postApiUploadsImagesPresignResponse401
  | postApiUploadsImagesPresignResponse500
) & {
  headers: Headers;
};

export type postApiUploadsImagesPresignResponse =
  | postApiUploadsImagesPresignResponseSuccess
  | postApiUploadsImagesPresignResponseError;

export const getPostApiUploadsImagesPresignUrl = () => {
  return `/api/uploads/images/presign`;
};

export const postApiUploadsImagesPresign = async (
  createImageUploadUrlInput: CreateImageUploadUrlInput,
  options?: RequestInit,
): Promise<postApiUploadsImagesPresignResponse> => {
  const res = await fetch(getPostApiUploadsImagesPresignUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createImageUploadUrlInput),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiUploadsImagesPresignResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as postApiUploadsImagesPresignResponse;
};

export const getPostApiUploadsImagesPresignMutationOptions = <
  TError = Error,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiUploadsImagesPresign>>,
    TError,
    { data: CreateImageUploadUrlInput },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiUploadsImagesPresign>>,
  TError,
  { data: CreateImageUploadUrlInput },
  TContext
> => {
  const mutationKey = ["postApiUploadsImagesPresign"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiUploadsImagesPresign>>,
    { data: CreateImageUploadUrlInput }
  > = (props) => {
    const { data } = props ?? {};

    return postApiUploadsImagesPresign(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiUploadsImagesPresignMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiUploadsImagesPresign>>
>;
export type PostApiUploadsImagesPresignMutationBody = CreateImageUploadUrlInput;
export type PostApiUploadsImagesPresignMutationError = Error;

export const usePostApiUploadsImagesPresign = <TError = Error, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiUploadsImagesPresign>>,
      TError,
      { data: CreateImageUploadUrlInput },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiUploadsImagesPresign>>,
  TError,
  { data: CreateImageUploadUrlInput },
  TContext
> => {
  return useMutation(getPostApiUploadsImagesPresignMutationOptions(options), queryClient);
};

export type getApiUsersResponse200 = {
  data: GetApiUsers200;
  status: 200;
};

export type getApiUsersResponseSuccess = getApiUsersResponse200 & {
  headers: Headers;
};

export type getApiUsersResponse = getApiUsersResponseSuccess;

export const getGetApiUsersUrl = () => {
  return `/api/users`;
};

export const getApiUsers = async (options?: RequestInit): Promise<getApiUsersResponse> => {
  const res = await fetch(getGetApiUsersUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiUsersResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getApiUsersResponse;
};

export const getGetApiUsersQueryKey = () => {
  return [`/api/users`] as const;
};

export const getGetApiUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiUsers>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiUsersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsers>>> = ({ signal }) =>
    getApiUsers({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUsers>>>;
export type GetApiUsersQueryError = unknown;

export function useGetApiUsers<TData = Awaited<ReturnType<typeof getApiUsers>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiUsers>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiUsers<TData = Awaited<ReturnType<typeof getApiUsers>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiUsers>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiUsers<TData = Awaited<ReturnType<typeof getApiUsers>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiUsers<TData = Awaited<ReturnType<typeof getApiUsers>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiUsersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetApiUsersSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiUsers>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiUsersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsers>>> = ({ signal }) =>
    getApiUsers({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getApiUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiUsersSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUsers>>>;
export type GetApiUsersSuspenseQueryError = unknown;

export function useGetApiUsersSuspense<
  TData = Awaited<ReturnType<typeof getApiUsers>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiUsersSuspense<
  TData = Awaited<ReturnType<typeof getApiUsers>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiUsersSuspense<
  TData = Awaited<ReturnType<typeof getApiUsers>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiUsersSuspense<
  TData = Awaited<ReturnType<typeof getApiUsers>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiUsersSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type postApiUsersResponse201 = {
  data: PostApiUsers201;
  status: 201;
};

export type postApiUsersResponse409 = {
  data: Error;
  status: 409;
};

export type postApiUsersResponseSuccess = postApiUsersResponse201 & {
  headers: Headers;
};
export type postApiUsersResponseError = postApiUsersResponse409 & {
  headers: Headers;
};

export type postApiUsersResponse = postApiUsersResponseSuccess | postApiUsersResponseError;

export const getPostApiUsersUrl = () => {
  return `/api/users`;
};

export const postApiUsers = async (
  createUserInput: CreateUserInput,
  options?: RequestInit,
): Promise<postApiUsersResponse> => {
  const res = await fetch(getPostApiUsersUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createUserInput),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiUsersResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as postApiUsersResponse;
};

export const getPostApiUsersMutationOptions = <TError = Error, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiUsers>>,
    TError,
    { data: CreateUserInput },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiUsers>>,
  TError,
  { data: CreateUserInput },
  TContext
> => {
  const mutationKey = ["postApiUsers"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiUsers>>,
    { data: CreateUserInput }
  > = (props) => {
    const { data } = props ?? {};

    return postApiUsers(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiUsersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUsers>>>;
export type PostApiUsersMutationBody = CreateUserInput;
export type PostApiUsersMutationError = Error;

export const usePostApiUsers = <TError = Error, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiUsers>>,
      TError,
      { data: CreateUserInput },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiUsers>>,
  TError,
  { data: CreateUserInput },
  TContext
> => {
  return useMutation(getPostApiUsersMutationOptions(options), queryClient);
};

export type getApiUsersBySlackUserIdResponse200 = {
  data: GetApiUsersBySlackUserId200;
  status: 200;
};

export type getApiUsersBySlackUserIdResponse404 = {
  data: Error;
  status: 404;
};

export type getApiUsersBySlackUserIdResponseSuccess = getApiUsersBySlackUserIdResponse200 & {
  headers: Headers;
};
export type getApiUsersBySlackUserIdResponseError = getApiUsersBySlackUserIdResponse404 & {
  headers: Headers;
};

export type getApiUsersBySlackUserIdResponse =
  | getApiUsersBySlackUserIdResponseSuccess
  | getApiUsersBySlackUserIdResponseError;

export const getGetApiUsersBySlackUserIdUrl = (slackUserId: string) => {
  return `/api/users/${slackUserId}`;
};

export const getApiUsersBySlackUserId = async (
  slackUserId: string,
  options?: RequestInit,
): Promise<getApiUsersBySlackUserIdResponse> => {
  const res = await fetch(getGetApiUsersBySlackUserIdUrl(slackUserId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiUsersBySlackUserIdResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getApiUsersBySlackUserIdResponse;
};

export const getGetApiUsersBySlackUserIdQueryKey = (slackUserId: string) => {
  return [`/api/users/${slackUserId}`] as const;
};

export const getGetApiUsersBySlackUserIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiUsersBySlackUserId>>,
  TError = Error,
>(
  slackUserId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUsersBySlackUserId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiUsersBySlackUserIdQueryKey(slackUserId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsersBySlackUserId>>> = ({
    signal,
  }) => getApiUsersBySlackUserId(slackUserId, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!slackUserId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiUsersBySlackUserId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiUsersBySlackUserIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiUsersBySlackUserId>>
>;
export type GetApiUsersBySlackUserIdQueryError = Error;

export function useGetApiUsersBySlackUserId<
  TData = Awaited<ReturnType<typeof getApiUsersBySlackUserId>>,
  TError = Error,
>(
  slackUserId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUsersBySlackUserId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsersBySlackUserId>>,
          TError,
          Awaited<ReturnType<typeof getApiUsersBySlackUserId>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiUsersBySlackUserId<
  TData = Awaited<ReturnType<typeof getApiUsersBySlackUserId>>,
  TError = Error,
>(
  slackUserId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUsersBySlackUserId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsersBySlackUserId>>,
          TError,
          Awaited<ReturnType<typeof getApiUsersBySlackUserId>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiUsersBySlackUserId<
  TData = Awaited<ReturnType<typeof getApiUsersBySlackUserId>>,
  TError = Error,
>(
  slackUserId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUsersBySlackUserId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiUsersBySlackUserId<
  TData = Awaited<ReturnType<typeof getApiUsersBySlackUserId>>,
  TError = Error,
>(
  slackUserId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUsersBySlackUserId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiUsersBySlackUserIdQueryOptions(slackUserId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetApiUsersBySlackUserIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiUsersBySlackUserId>>,
  TError = Error,
>(
  slackUserId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsersBySlackUserId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiUsersBySlackUserIdQueryKey(slackUserId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsersBySlackUserId>>> = ({
    signal,
  }) => getApiUsersBySlackUserId(slackUserId, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getApiUsersBySlackUserId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiUsersBySlackUserIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiUsersBySlackUserId>>
>;
export type GetApiUsersBySlackUserIdSuspenseQueryError = Error;

export function useGetApiUsersBySlackUserIdSuspense<
  TData = Awaited<ReturnType<typeof getApiUsersBySlackUserId>>,
  TError = Error,
>(
  slackUserId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsersBySlackUserId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiUsersBySlackUserIdSuspense<
  TData = Awaited<ReturnType<typeof getApiUsersBySlackUserId>>,
  TError = Error,
>(
  slackUserId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsersBySlackUserId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiUsersBySlackUserIdSuspense<
  TData = Awaited<ReturnType<typeof getApiUsersBySlackUserId>>,
  TError = Error,
>(
  slackUserId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsersBySlackUserId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiUsersBySlackUserIdSuspense<
  TData = Awaited<ReturnType<typeof getApiUsersBySlackUserId>>,
  TError = Error,
>(
  slackUserId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiUsersBySlackUserId>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiUsersBySlackUserIdSuspenseQueryOptions(slackUserId, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
